import { IsString, IsNotEmpty, Matches } from 'class-validator';
import { ApiProperty } from '@nestjs/swagger';

export class SignInDto {
  @ApiProperty({
    description: 'The wallet address (e.g., Ethereum address)',
    example: '0x742d35Cc6634C0532925a3b8D404fddaF1f71d78',
  })
  @IsString()
  @IsNotEmpty()
  @Matches(/^0x[a-fA-F0-9]{40}$/, {
    message: 'wallet_address must be a valid Ethereum address',
  })
  wallet_address: string;

  @ApiProperty({
    description: 'The signature generated by signing the nonce with the wallet',
    example:
      '0x1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef1b',
  })
  @IsString()
  @IsNotEmpty()
  @Matches(/^0x[a-fA-F0-9]{130}$/, {
    message: 'signature must be a valid Ethereum signature',
  })
  signature: string;
}
